# Generated by Django 4.1.3 on 2022-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_addressuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
